replicaCount: 3
image:
  repository: mauricethomas/goapp-mutating-webhook
  pullPolicy: IfNotPresent
  tag: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
config:
  go_mem_limit_factor: 0.95
serviceMonitor:
  extraLabels:
    release: prometheus
webhookConfiguration:
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded
  objectSelector:
    matchExpressions:
      - key: mutate
        operator: In
        values:
          - "true"
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
service:
  type: ClusterIP
  port: 443
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
startupProbe:
  httpGet:
    path: /healthz
    port: 443
    scheme: HTTPS
  periodSeconds: 5
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /healthz
    port: 443
    scheme: HTTPS
  periodSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /healthz
    port: 443
    scheme: HTTPS
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 3
nodeSelector: {}
# image is not compiled for arm64 yet
# kubernetes.io/arch: "amd64"

tolerations: []
affinity: {}
