kind: Deployment
apiVersion: apps/v1
metadata:
  name: mutating-webhook
  namespace: mutating-webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mutating-webhook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
        - name: mutating-webhook
          image: mutating-webhook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          env:
            - name: GIN_MODE
              value: release
            - name: LOG_FORMAT
              value: json
          command:
          - /mutating-webhook
          - -cert=/tls/tls.crt
          - -key=/tls/tls.key
          - -config=/etc/config/config.yaml
          volumeMounts:
            - name: certificate
              mountPath: /tls
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
          resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 100Mi
              cpu: 200m
          startupProbe:
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 3
      volumes:
        - name: certificate
          secret:
            secretName: mutation-webhook-certificate
        - name: config
          configMap:
            name: mutating-webhook