kind: Service
apiVersion: v1
metadata:
  name: mutating-webhook
  namespace: mutating-webhook
  labels:
    app: "mutating-webhook"
spec:
  selector:
    app: mutating-webhook
  ports:
    - port: 443
      targetPort: 443
