apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goapp-mutating-webhook.fullname" . }}-config
  labels:
    {{- include "goapp-mutating-webhook.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
